package com.toutiao.model;

public enum InterfaneName {
    TTHOST,
    TJURL,GSLIST,SHARE,ACTIVITYLIST,

    LTHOST,
    LOGIN,POSTDEMO,USER,GETLIST,MYLOOK,GETPARAM,
    GETJSON,GCURL,EXPURL,BBSLOOK,REPLYURL,SEARCHURL,
    LIKEURL,FAVORITE,EXPERTHOME,GETPUB,GETPREDICT,USERCENTER,
    MYITEM,MYFAVOR,MYREPLY,



}
