package com.toutiao.model;

public enum InterfaneName {
    TTHOST,
    TJURL,

    LTHOST,
    LOGIN,POSTDEMO,USER,GETLIST,MYLOOK,GETPARAM,
    GETJSON,GCURL,EXPURL,BBSLOOK,REPLYURL,SEARCHURL,
    LIKEURL,FAVORITE,EXPERTHOME

}
